### ISSUE TITLE
Stop respawning `lockscreen-app` un unlock

### ISSUE THREAD

**Issue by Saviq** [Miriway/Miriway#91]
If the lockscreen app happens to have a problem and crashes on startup (but after it's able to acquire the screen lock), Miriway will continue respawning it even after the session is unlocked through logind.

This means the session becomes unusable, as unlocking it just triggers another lock with the respawned app.

**Comment by AlanGriffiths** [comment]
Isn't that the desired behaviour? If a lockscreen crashes instead of authenticating, then the session should remain locked

**Comment by Saviq** [comment]
No, you should still be able to unlock e.g. in GDM, that's not possible today if the lockscreen has problems.

**Comment by mattkae** [comment]
Commenting this here for future's sake. I believe this ticket covers two distinct issues:

1. The lockscreen dies after it acquires the lock, causing another lockscreen to want to spawn while the first lockscreen is trying to respawn. This is due to the `on_lock` event _maybe_ getting fired off.
2. And, the lockscreen gets spawned but crashes, causing it to respawn in a loop, but it can never respawn. But, if the session actually gets unlocked (via logind or something), then we should stop trying to respawn the initial lockscreen

**Comment by mattkae** [comment]
Eh, maybe 1. can't happen and I am overthinking that...

**Comment by Saviq** [comment]
+1 on 2. above, and on ! 1. above.
